export const GET_CABINETS = 'GET_CABINETS';
export const GET_MODAL_CABINETS = 'GET_MODAL_CABINETS';
export const GET_CABINET = 'GET_CABINET';
export const UPDATE_CABINET = 'UPDATE_CABINET';
export const CREATE_CABINET = 'CREATE_CABINET';
